// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzec2cEMjri0zSwEbiDj3OVWL_pV8x0wk',
    appId: '1:1017946313744:web:359086d3e02e1f9357e695',
    messagingSenderId: '1017946313744',
    projectId: 'store-enyad',
    authDomain: 'store-enyad.firebaseapp.com',
    databaseURL: 'https://store-enyad-default-rtdb.firebaseio.com',
    storageBucket: 'store-enyad.appspot.com',
    measurementId: 'G-6FD0RQFE56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAcvk04dscG6wjrYGzgr3UDB5ethLU6_E',
    appId: '1:1017946313744:android:e7c96bbf399b3a4b57e695',
    messagingSenderId: '1017946313744',
    projectId: 'store-enyad',
    databaseURL: 'https://store-enyad-default-rtdb.firebaseio.com',
    storageBucket: 'store-enyad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb-lRmo_eDa_ujC_xtgJOVChXAX4OZV08',
    appId: '1:1017946313744:ios:ce812e70df15b16657e695',
    messagingSenderId: '1017946313744',
    projectId: 'store-enyad',
    databaseURL: 'https://store-enyad-default-rtdb.firebaseio.com',
    storageBucket: 'store-enyad.appspot.com',
    androidClientId: '1017946313744-91p9n54aslo13vp4jkcd183qp4o3drl1.apps.googleusercontent.com',
    iosClientId: '1017946313744-e8qqll81fb278jak0oipknobc0thvbbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.enyadStore3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb-lRmo_eDa_ujC_xtgJOVChXAX4OZV08',
    appId: '1:1017946313744:ios:ce812e70df15b16657e695',
    messagingSenderId: '1017946313744',
    projectId: 'store-enyad',
    databaseURL: 'https://store-enyad-default-rtdb.firebaseio.com',
    storageBucket: 'store-enyad.appspot.com',
    androidClientId: '1017946313744-91p9n54aslo13vp4jkcd183qp4o3drl1.apps.googleusercontent.com',
    iosClientId: '1017946313744-e8qqll81fb278jak0oipknobc0thvbbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.enyadStore3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzec2cEMjri0zSwEbiDj3OVWL_pV8x0wk',
    appId: '1:1017946313744:web:56ab847f007ec66d57e695',
    messagingSenderId: '1017946313744',
    projectId: 'store-enyad',
    authDomain: 'store-enyad.firebaseapp.com',
    databaseURL: 'https://store-enyad-default-rtdb.firebaseio.com',
    storageBucket: 'store-enyad.appspot.com',
    measurementId: 'G-QRH5NH5CGL',
  );

}